docs: Add Layout documentation
edge-js/edgejs.dev pull request #6
Opened 2024-05-14 22:33 UTC by kraimbaud

### ❓ Type of change

- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving doc)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Add usage of template and slots in documentation as is was complicated to find

2024-05-25 19:17 UTC, RomainLanz requested changes

2024-05-25 19:17 UTC, RomainLanz commented on content/docs/components/layouts.md
> +You can use slots to render templates. Let's create a `index.edge` file inside the `views/components/layout` directory.
```suggestion
You can use slots to render templates. Let's create a `app.edge` file inside the `views/components/layout` directory.
```

2024-05-25 19:17 UTC, RomainLanz commented on content/docs/components/layouts.md
> +<!DOCTYPE html>
```suggestion
// title: views/components/layout/app.edge
<!DOCTYPE html>
```

2024-05-25 19:17 UTC, RomainLanz commented on content/docs/components/layouts.md
> +@layout({ title: "Welcome page title" })
```suggestion
```edge
// title: views/welcome.edge
@layout.app({ title: "Welcome page title" })
```

2024-05-25 19:18 UTC, RomainLanz commented
Hey! 👋🏻 

Thanks for your PR!

I am not sure if this section should be inside the `Component` category or in the `Guides` category.
What are your thoughts @thetutlage @Julien-R44?

2024-05-31 09:23 UTC, kraimbaud commented
@RomainLanz I have made your change ;)

2024-06-03 13:46 UTC, merged

2024-06-03 13:46 UTC, RomainLanz commented
Thanks!